Clash/urls.py
from django.contrib import admin
from django.urls import path, include
from .models import *
from . import views

urlpatterns = [
    #admin
    path('admin/', admin.site.urls),
    path('pedidos/', views.PedidoListView.as_view(), name='lista_pedidos_admin'),

    # URLs de autenticação e perfil
    path('', views.home, name='home'),
    path('login/', views.PaginaLogin.as_view(), name='login'),
    path('logout/', views.PaginaLogout.as_view(), name='logout'),
    path('registro/', views.PaginaRegistro.as_view(), name='registro'),
    path('editar-perfil/', views.PaginaUserChange.as_view(), name='editar_perfil'),
    # URLs de CRUD de Notícias
    path('noticias/', views.NoticiaListView.as_view(), name='noticia_list'),
    path('noticias/nova/', views.NoticiaCreateView.as_view(), name='noticia_create'),
    path('noticias/<int:pk>/', views.NoticiaDetailView.as_view(), name='noticia_detail'),
    path('noticias/<int:pk>/editar/', views.NoticiaUpdateView.as_view(), name='noticia_update'),
    path('noticias/<int:pk>/deletar/', views.NoticiaDeleteView.as_view(), name='noticia_delete'),
    # URLs de CRUD de produtos
    path('produtos/', views.ProdutoListView.as_view(), name='produto_list'),
    path('produtos/novo/', views.ProdutoCreateView.as_view(), name='produto_create'),
    path('produtos/<int:pk>/', views.ProdutoDetailView.as_view(), name='produto_detail'),
    path('produtos/<int:pk>/editar/', views.ProdutoUpdateView.as_view(), name='produto_update'),
    path('produtos/<int:pk>/deletar/', views.ProdutoDeleteView.as_view(), name='produto_delete'),

    # URLs de CRUD DE PARTIDAS
    path('partidas/', views.PartidaListView.as_view(), name='partida_list'),
    path('partidas/nova/', views.PartidaCreateView.as_view(), name='partida_create'),
    path('partidas/<int:pk>/', views.PartidaDetailView.as_view(), name='partida_detail'),
    path('partidas/<int:pk>/editar/', views.PartidaUpdateView.as_view(), name='partida_update'),
    path('partidas/<int:pk>/deletar/', views.PartidaDeleteView.as_view(), name='partida_delete'),
    # URLs do carrinho de compras
    path('carrinho/adicionar/<int:pk>/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('carrinho/', views.CarrinhoView.as_view(), name='ver_carrinho'),
    path('carrinho/atualizar/<int:pk>/', views.atualizar_item_carrinho, name='atualizar_item'),
    path('carrinho/remover/<int:pk>/', views.remover_item_carrinho, name='remover_item'),
    path('carrinho/finalizar/', views.finalizar_compra, name='finalizar_compra'),
    
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Clash.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Clash/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date
import uuid
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver
import os
#__________________________________________
#|                                        |
#|           funções auxiliares           |
#|________________________________________|

# Função para o campo Foto_Jogador
def gerar_caminho_foto_jogador(instance, filename):
    extensao = filename.split('.')[-1]
    nome_arquivo = f'{uuid.uuid4()}.{extensao}'
    return f'fotos_jogador/{nome_arquivo}'

# Função para o campo Foto_Perfil
def gerar_caminho_foto_perfil(instance, filename):
    extensao = filename.split('.')[-1]
    nome_arquivo = f'{uuid.uuid4()}.{extensao}'
    return f'fotos_perfil/{nome_arquivo}'

# Função para o campo Foto_Produto
def gerar_caminho_imagem_produto(instance, filename):
    extensao = filename.split('.')[-1]
    nome_arquivo = f'{uuid.uuid4()}.{extensao}'
    return f'fotos_produtos/{nome_arquivo}'

#_______________________________________________
#|                                             |
#|        as tabelas do banco de dados         |
#|_____________________________________________|

#relativos a usuários e autenticação
# Modelo customizado de usuário que herda de AbstractUser.
class tbUser(AbstractUser):
    Data_Nascimento = models.DateField(null=True, blank=True)
    Foto_Perfil = models.ImageField(
        upload_to=gerar_caminho_foto_perfil,
        null=True,
        blank=True,
    )
    # Propriedade que calcula a idade com base na Data_Nascimento.
    @property
    def idade(self):
        if self.Data_Nascimento:
            hoje = date.today()
            return hoje.year - self.Data_Nascimento.year - (
                (hoje.month, hoje.day) < (self.Data_Nascimento.month, self.Data_Nascimento.day)
            )
        return None

class tbCartao(models.Model):
    Tipo_Cartao = models.CharField(max_length = 50)
    Numero_Cartao = models.CharField(max_length = 16)
    Nome_Cartao = models.CharField(max_length = 100)

class tbJogador(models.Model):
    Nome = models.CharField(max_length = 100)
    Nickname = models.CharField(max_length = 50)
    Data_Nascimento = models.DateField(null = True, blank = True)
    sobre = models.TextField()
    trofeus = models.IntegerField(default = 0)
    Foto_Jogador = models.ImageField(
        upload_to = gerar_caminho_foto_jogador, 
        null = True,
        blank = True,
    )
    @property
    def idade(self):
        if self.Data_Nascimento:
            hoje = date.today()
            return hoje.year - self.Data_Nascimento.year - (
                (hoje.month, hoje.day) < (self.Data_Nascimento.month, self.Data_Nascimento.day)
            )
        return None
    
    def __str__(self):
        return self.Nickname

def _delete_file(path):
    if os.path.isfile(path):
        os.remove(path)

@receiver(post_delete, sender=tbUser)
@receiver(post_delete, sender=tbJogador)
def delete_image_on_delete(sender, instance, **kwargs):
    # Verifica tbUser
    if sender == tbUser and instance.Foto_Perfil:
        _delete_file(instance.Foto_Perfil.path)
    
    # Verifica tbJogador
    if sender == tbJogador and instance.Foto_Jogador:
        _delete_file(instance.Foto_Jogador.path)

@receiver(pre_save, sender=tbUser)
@receiver(pre_save, sender=tbJogador)
def delete_old_image_on_update(sender, instance, **kwargs):
    if not instance.pk:
        return False
    try:
        old_instance = sender.objects.get(pk=instance.pk)
    except sender.DoesNotExist:
        return False
    # Lógica para tbUser
    if sender == tbUser:
        try:
            old_file = old_instance.Foto_Perfil
            new_file = instance.Foto_Perfil
            if old_file and old_file != new_file:
                _delete_file(old_file.path)
        except ValueError:
            pass

    # Lógica para tbJogador
    if sender == tbJogador:
        try:
            old_file = old_instance.Foto_Jogador
            new_file = instance.Foto_Jogador
            if old_file and old_file != new_file:
                _delete_file(old_file.path)
        except ValueError:
            pass

#relativos a conteúdo e entretenimento
class tbPartida(models.Model):
    Data_Prevista = models.DateTimeField()
    Time_Adversario = models.CharField(max_length = 100)
    Modalidade = models.CharField(max_length = 50)

class tbJogador_Partida(models.Model):
    tbJogador = models.ForeignKey(tbJogador, on_delete=models.CASCADE)
    tbPartida = models.ForeignKey(tbPartida, on_delete=models.CASCADE)

class tbStream(models.Model):
    partida = models.ForeignKey(
        tbPartida, 
        on_delete=models.CASCADE,
        related_name='transmissoes',
    )
    tipo = models.CharField(max_length=50)
    embed = models.TextField()

    class Meta:
        verbose_name = "Transmissão"
        verbose_name_plural = "Transmissões"

    def __str__(self):
        return f"Transmissão de '{self.partida.nome}' via {self.tipo}"

class tbNoticia(models.Model):
    Titulo = models.CharField(max_length=100)
    TextoHTML = models.TextField()
    Partida = models.ForeignKey(
        tbPartida,
        on_delete=models.CASCADE,
        null=True, 
        blank=True,
    )

class tbEdita(models.Model):
    Data_Edicao = models.DateField(auto_now_add=True)
    tbUser = models.ForeignKey(tbUser, on_delete=models.CASCADE)
    tbNoticia = models.ForeignKey('tbNoticia', on_delete=models.CASCADE)

#relativos a compras e vendas
class tbCarrinho(models.Model):
    User = models.ForeignKey(tbUser, on_delete=models.CASCADE)
    @property
    def preco_total(self):
        itens = self.itens.all()
        total = sum([item.valor_total for item in itens])
        return total

class tbProduto(models.Model):
    nome = models.CharField(max_length=255)
    descricao = models.TextField(null=True, blank=True)
    tipo = models.CharField(max_length=100, blank=True)
    preco_compra = models.DecimalField(max_digits=10, decimal_places=2)
    preco_venda = models.DecimalField(max_digits=10, decimal_places=2)
    estoque = models.PositiveIntegerField(default=0)
    especificacoes = models.ManyToManyField(
        'tbFoto', 
        through='tbEspecifica', 
        related_name='produtos_especificados',
    )
    class Meta:
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"
    def __str__(self):
        return self.nome

class tbFoto(models.Model):
    produto = models.ForeignKey(
        tbProduto, 
        on_delete=models.CASCADE, 
        related_name='Foto',
    )
    foto = models.ImageField(
        upload_to=gerar_caminho_imagem_produto,
        null=True,
        blank=True,
    )
    class Meta:
        verbose_name = "Foto"
        verbose_name_plural = "Fotos"
    def __str__(self):
        return f"Foto de {self.produto.nome}"

class tbTipoEspecificacao(models.Model):
    nome = models.CharField(max_length=50) # Ex: "Cor", "Tamanho"
    def __str__(self):
        return self.nome

class tbEspecifica(models.Model):
    produto = models.ForeignKey(tbProduto, on_delete=models.CASCADE)
    foto = models.ForeignKey(tbFoto, on_delete=models.CASCADE)
    tipo = models.ForeignKey(tbTipoEspecificacao, on_delete=models.CASCADE, null=True)
    descricao = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        unique_together = ('produto', 'foto')
        verbose_name = "Especificação"
        verbose_name_plural = "Especificações"
    def __str__(self):
        return f"Especificação de {self.produto.nome} com a foto ID {self.foto.id}"

class tbCompra(models.Model):
    carrinho = models.ForeignKey(
        tbCarrinho, 
        on_delete=models.CASCADE, 
        related_name='itens',
    )
    produto = models.ForeignKey(
        tbProduto, 
        on_delete=models.CASCADE,
    )
    especificacoes = models.ManyToManyField(tbEspecifica, blank=True)
    quantidade = models.PositiveIntegerField(default=1)
    valor_compra = models.DecimalField(max_digits=10, decimal_places=2) 
    frete = models.DecimalField(
        max_digits = 10, 
        decimal_places = 2, 
        default = 0
    )
    @property
    def valor_total(self):
        return (self.valor_compra * self.quantidade) + self.frete
    class Meta:
        verbose_name = "Item de Compra"
        verbose_name_plural = "Itens de Compra"
    def __str__(self):
        return f"{self.quantidade}x {self.produto.nome} no Carrinho {self.carrinho.id}"

class tbPedido(models.Model):
    STATUS_CHOICES = (
        ('Pendente', 'Pendente'),
        ('Aprovado', 'Aprovado'),
        ('Enviado', 'Enviado'),
        ('Entregue', 'Entregue'),
        ('Cancelado', 'Cancelado'),
    )
    user = models.ForeignKey(tbUser, on_delete=models.CASCADE, related_name='pedidos')
    data_pedido = models.DateTimeField(auto_now_add=True)
    valor_total = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pendente')

    class Meta:
        verbose_name = "Pedido"
        verbose_name_plural = "Pedidos"

    def __str__(self):
        return f"Pedido #{self.id} de {self.user.username}"

class tbItemPedido(models.Model):
    pedido = models.ForeignKey(tbPedido, on_delete=models.CASCADE, related_name='itens')
    produto = models.ForeignKey(tbProduto, on_delete=models.SET_NULL, null=True) # Se o produto for deletado, o histórico permanece
    # Copiamos o nome do produto caso ele seja deletado futuramente
    nome_produto = models.CharField(max_length=255) 
    quantidade = models.PositiveIntegerField()
    preco_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    # Como as especificações podem mudar, podemos salvar como texto para histórico simples
    especificacoes_texto = models.TextField(blank=True, null=True) 

    class Meta:
        verbose_name = "Item do Pedido"

Clash/views/geral.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView
from django.urls import reverse_lazy
from ..models import tbJogador, tbProduto, tbNoticia, tbUser
from ..forms import CustomUserCreationForm, CustomUserChangeForm

def home(request):
    lista_jogadores = tbJogador.objects.all()
    lista_produtos = tbProduto.objects.all()
    lista_noticias = tbNoticia.objects.all().order_by('-id')[:3]
    
    contexto = {
        'jogadores': lista_jogadores,
        'produtos': lista_produtos,
        'noticias': lista_noticias,
    }
    return render(request, 'Clash/base.html', contexto)

class PaginaLogin(LoginView):
    template_name = 'Clash/login.html'
    def get_success_url(self):
        return reverse_lazy('home')

class PaginaLogout(LogoutView):
    def get_next_page(self):
        return redirect('home')

class PaginaRegistro(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'Clash/registro.html' 
    success_url = reverse_lazy('login')

class PaginaUserChange(LoginRequiredMixin, UpdateView):
    model = tbUser
    form_class = CustomUserChangeForm
    template_name = 'Clash/edit_user.html'
    success_url = reverse_lazy('home')
    def get_object(self, queryset=None):
        return self.request.user

Clash/views/partida.py
from django.urls import reverse_lazy
from django.db import transaction
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from ..models import tbPartida
from ..forms import PartidaForm, StreamFormSet # Supondo que StreamFormSet está no forms.py

class PartidaListView(ListView):
    model = tbPartida
    template_name = 'Clash/partida_list.html'
    context_object_name = 'partidas'
    ordering = ['-Data_Prevista']

class PartidaDetailView(DetailView):
    model = tbPartida
    template_name = 'Clash/partida_detail.html'
    context_object_name = 'partida'

class PartidaCreateView(LoginRequiredMixin, CreateView):
    model = tbPartida
    form_class = PartidaForm
    template_name = 'Clash/partida_form.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['streams'] = StreamFormSet(self.request.POST)
        else:
            data['streams'] = StreamFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        streams = context['streams']
        
        with transaction.atomic():
            self.object = form.save()
            if streams.is_valid():
                streams.instance = self.object
                streams.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('partida_detail', kwargs={'pk': self.object.pk})

class PartidaUpdateView(LoginRequiredMixin, UpdateView):
    model = tbPartida
    form_class = PartidaForm
    template_name = 'Clash/partida_form.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['streams'] = StreamFormSet(self.request.POST, instance=self.object)
        else:
            data['streams'] = StreamFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        streams = context['streams']
        with transaction.atomic():
            self.object = form.save()
            if streams.is_valid():
                streams.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('partida_detail', kwargs={'pk': self.object.pk})

class PartidaDeleteView(LoginRequiredMixin, DeleteView):
    model = tbPartida
    template_name = 'Clash/partida_confirm_delete.html'
    success_url = reverse_lazy('partida_list')

Clash/templates/Clash/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Royal Elixir: A equipe de Clash Royale{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="author" content="Ana Luiza Saldanha e Nicolly Moura">
    <meta name="description" content="Site Inicial sobre a equipe e o jogo.">

    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <meta property="og:title" content="Royal Elixir">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extra_head %}{% endblock %}
</head>

<body>
    <header>
        <div class="logo">
            <img src="{% static 'imgs/logo_royal_elixir.jpg' %}" alt="logo">
            <h1>Royal Elixir</h1>
        </div>
        <nav>
            {% if user.is_authenticated %}
                <a href="{% url 'ver_carrinho' %}" style="display: flex; align-items: center; text-decoration: none; color: rgb(252, 255, 203); font-weight: bold;" title="Meu Carrinho">
                🛒
                </a>
                <div style="display: flex; align-items: center; gap: 10px;">
                    {% if user.Foto_Perfil %}
                        <img src="{{ user.Foto_Perfil.url }}" alt="Foto Perfil" style="height:30px; width:30px; border-radius:50%; vertical-align:middle; object-fit: cover;">
                    {% endif %}
                    <span style="color: rgb(252, 255, 203);">{{ user.username }}</span>
                    <form method="post" action="{% url 'logout' %}" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" style="background:none; border:none; color:violet; cursor:pointer; font-weight:bold; font-size:16px; font-family: inherit;">Sair</button>
                    </form>
                </div>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
                {% endif %}

            <a href="{% url 'home' %}#sobre">Sobre</a>
            <a href="{% url 'produto_list' %}">Loja</a>
            <a href="{% url 'noticia_list' %}">Notícias</a>
            <a href="{% url 'partida_list' %}">Partidas</a>
            {%if user.is_superuser%}
                <a href="{% url 'lista_pedidos_admin' %}">Pedidos</a>
            {% endif %}
            
            {% block extra-nav-header %}{% endblock %}
        </nav>
    </header>

    {% block content %}
    <section id="sobre">
        <h2>Sobre a equipe e o jogo</h2>
        
        <div class="text-card">
            <div class="text-content">
                <h3>O que é Clash Royale?</h3>
                <p>
                    <strong>Clash Royale</strong> é um jogo de estratégia em tempo real criado pela 
                    <strong>Supercell</strong> e lançado em <strong>2 de março de 2016</strong>. 
                    O título combina de forma inovadora <em>cartas colecionáveis</em>, 
                    <em>defesa de torres</em> e batalhas dinâmicas.
                </p>
            </div>
            <div class="text-image">
                <img src="{% static 'imgs/cr_imagen1.jpg' %}" alt="Clash Royale imagem 1">
            </div>
        </div>

        <div class="text-card">
            <div class="text-content">
                <h4>Principais características</h4>
                <ul>
                    <li><strong>Cartas colecionáveis:</strong> desbloqueie, evolua e monte decks com tropas, feitiços e construções únicas.</li>
                    <li><strong>Arenas de batalha:</strong> avance por diferentes arenas conforme conquista vitórias.</li>
                    <li><strong>Clãs:</strong> junte-se a outros jogadores para compartilhar cartas, treinar e competir em guerras de clãs.</li>
                    <li><strong>Modos de jogo:</strong> participe de partidas rápidas 1x1, batalhas cooperativas 2x2 e eventos especiais.</li>
                </ul>
            </div>
            <div class="text-image">
                <img src="{% static 'imgs/cr_imagen2.jpg' %}" alt="Clash Royale imagem 2">
            </div>
        </div>

        <div class="text-card">
            <div class="text-content">
                <h4>Por que jogar?</h4>
                <p>
                    Com uma <strong>jogabilidade acessível e competitiva</strong>, 
                    Clash Royale oferece partidas curtas, intensas e estratégicas, perfeitas 
                    para momentos casuais ou para desafios no <strong>cenário de eSports</strong>.
                </p>
            </div>
            <div class="text-image">
                <img src="{% static 'imgs/cr_imagen3.jpg' %}" alt="Clash Royale imagem 3">
            </div>
        </div>
    </section>

    <section id="perfil">
        <h2>Nossos Jogadores</h2>
        <div class="players-info" style="display: flex; flex-wrap: wrap; justify-content: center; gap: 20px;">
            {% for jogador in jogadores %}
            <div class="player-card">
                {% if jogador.Foto_Jogador %}
                    <img src="{{ jogador.Foto_Jogador.url }}" alt="Foto de {{ jogador.Nickname }}">
                {% else %}
                    <img src="{% static 'imgs/default_player.png' %}" alt="Sem foto">
                {% endif %}
                
                <div>
                    <h4>{{ jogador.Nome }}</h4>
                    <p>Nickname: {{ jogador.Nickname }}</p>
                    
                    {% if jogador.idade %}
                        <p>Idade: {{ jogador.idade }} Anos</p>
                    {% else %}
                        <p>Idade: N/D</p>
                    {% endif %}
                    
                    <p>Troféus: {{ jogador.trofeus }}</p>
                    <p>Sobre: {{ jogador.sobre|truncatechars:30 }}</p>
                </div>
            </div>
            {% empty %}
                <p>Nenhum jogador cadastrado.</p>
            {% endfor %}
        </div>
    </section>


    <section id="loja">
        <h2>Loja</h2>
        <p>Aqui você poderá comprar itens exclusivos da equipe Royal Elixir.</p>

        <div class="store">
            {% for produto in produtos %}
            <div class="item">
                <div class="carousel">
                    {% if produto.Foto.all %}
                        {% for foto in produto.Foto.all %}
                            <img src="{{ foto.foto.url }}" class="{% if forloop.first %}active{% endif %}" alt="Foto {{ produto.nome }}">
                        {% endfor %}
                        
                        {% if produto.Foto.count > 1 %}
                            <button class="prev">&#10094;</button>
                            <button class="next">&#10095;</button>
                        {% endif %}
                    {% else %}
                        <img src="{% static 'imgs/no-image.png' %}" class="active" alt="Sem Imagem">
                    {% endif %}
                </div>
                
                <h3>{{ produto.nome }}</h3>
                {% if produto.tbespecifica_set.exists %}
                    <p style="font-size: 0.9rem;">Várias opções disponíveis</p>
                {% else %}
                    <p>Tamanho Único</p>
                {% endif %}
                
                <p>R$ {{ produto.preco_venda }}</p>
                
                <a href="{% url 'produto_detail' produto.pk %}" style="display:inline-block; background-color:violet; color:white; padding:8px 15px; border-radius:5px; text-decoration:none; margin-top:10px; font-weight:bold;">Ver Detalhes</a>
            </div>
            {% empty %}
                <p>Nenhum produto disponível.</p>
            {% endfor %}
        </div>
    </section>
        
        
    <section id="noticias">
        <h2>Últimas Notícias</h2>
        <div class="news-container">
            {% for noticia in noticias %}
            <div class="news-card">
                <img src="{% static 'imgs/cr_imagen3.jpg' %}" alt="Imagem notícia" style="width:100%; height:150px; object-fit:cover; border-radius:8px;">
                
                <div class="news-info">
                    <span class="category">ROYAL NEWS</span> | 
                    <span class="date">{{ noticia.tbedita_set.first.Data_Edicao|date:"d/m/Y" }}</span>
                    
                    <h3>{{ noticia.Titulo }}</h3>
                    <p>{{ noticia.TextoHTML|striptags|truncatewords:20 }}</p>
                    
                    <a href="{% url 'noticia_detail' noticia.pk %}" style="color:violet; font-weight:bold;">Saiba mais >></a>
                </div>
            </div>
            {% empty %}
                <p>Nenhuma notícia publicada.</p>
            {% endfor %}
        </div>
    </section>

    <div class="lives" style="text-align: center; margin-top: 50px; padding-bottom: 50px;">
        <h2 style="color: rgb(252, 255, 203);">Transmissões ao Vivo</h2>
        <div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 20px; margin-top: 20px;">
            <section>
                <p>LIVE DO YOUTUBE</p>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/VIDEO_ID" 
                title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; 
                gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </section>

            <section>
                <p>LIVE DA TWITCH</p>
                <iframe
                src="https://player.twitch.tv/?channel=jacksoono&parent=127.0.0.1"
                frameborder="0"
                allowfullscreen="true"
                scrolling="no"
                height="315"
                width="560">
                </iframe>
            </section>
        </div>
    </div>

    {% endblock %} 
    <script>
        document.querySelectorAll('.carousel').forEach(carousel => {
            const images = carousel.querySelectorAll('img');
            
            // Só ativa se tiver mais de 1 imagem
            if (images.length <= 1) return;

            let currentIndex = 0;

            const showImage = index => {
                images.forEach((img, i) => {
                    img.classList.toggle('active', i === index);
                });
            };

            const prevBtn = carousel.querySelector('.prev');
            const nextBtn = carousel.querySelector('.next');

            if(prevBtn) {
                prevBtn.addEventListener('click', (e) => {
                    e.preventDefault(); // Evita pular a página ao clicar
                    currentIndex = (currentIndex - 1 + images.length) % images.length;
                    showImage(currentIndex);
                });
            }

            if(nextBtn) {
                nextBtn.addEventListener('click', (e) => {
                    e.preventDefault();
                    currentIndex = (currentIndex + 1) % images.length;
                    showImage(currentIndex);
                });
            }
        });
    </script>  
    {% block Scripts %}
    {% endblock %}
</body>
</html>

Clash/templates/Clash/edit_user.html
{% extends "Clash/base.html" %}

{% block title %}Editar Usuário{% endblock %}



{% block content %}
    <h3>Editar Usuário</h3>

    <!-- Formulário que envia dados via POST para a mesma URL -->
    <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
{% endblock %}

{% block Scripts %}
    
{% endblock %}

Clash/templates/Clash/noticia_confirm_delete.html
{% extends 'Clash/base.html' %}

{% block content %}
<div class="container">
    <h2>Confirmar Exclusão</h2>
    <hr>
    <p>Você tem certeza que deseja deletar a notícia: 
        <strong>"{{ object.Titulo }}"</strong>?
    </p>
    
    <p class="text-danger">Esta ação não pode ser desfeita.</p>
    
    <form method="post">
        {% csrf_token %}
        <a href="{% url 'noticia_detail' object.pk %}" class="btn btn-secondary">Cancelar</a>
        <button type="submit" class="btn btn-danger">Sim, Deletar</button>
    </form>
</div>
{% endblock %}